server {
    listen 80;

    # Serve frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # API routes → backend
    location /users {
        proxy_pass http://app:3000;
    }

    location /init {
        proxy_pass http://app:3000;
    }
}
